security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success-handler: lexik_jwt_authentication.handler.authentication_success
                failure-handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api|^/admin
            stateless: true
            provider: app_user_provider
            jwt: ~

        logout:
            pattern: ^/api/logout
            stateless: true

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}    
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_USER }
monolog:    
    channels: ['security']
    handlers:
        security:
            type: stream
            path: "%kernel.logs_dir%/security.log"
            level: debug